@url = http://localhost:55514

### create discount
POST {{url}}/discounts
Content-Type: application/json

{
    "customerId": "d9964eeb-8602-4553-bc09-0309c3f9ee73",
    "code": "PROMO",
    "percentage": 20
}